#!/bin/bash

# Carica la configurazione
source "$(dirname "$0")/config.sh"

if [ "$1" == "-s" ]; then
    #echo "Unmounting $LOCAL_DIR_TEL..."
    notify-send "Unmounting $LOCAL_DIR_TEL..."
    fusermount -u $LOCAL_DIR_TEL
    exit 0
elif [ "$1" == "-m" ]; then

    # Controlla se il telefono risponde al ping
    ping -c 1 -W 1 "$IP_TEL" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        #echo "Telefono raggiungibile. Procedo con il mount..."
        notify-send "Telefono raggiungibile. Procedo con il mount..."

        # Controlla se è già montato
        mount | grep "$LOCAL_DIR_TEL" > /dev/null
        if [ $? -eq 0 ]; then
            #echo "È già montato su $LOCAL_DIR_TEL"
            notify-send "È già montato su $LOCAL_DIR_TEL"
        else
            sshfs -p $PORT_TEL $USER_TEL@$IP_TEL:$REMOTE_DIR_TEL $LOCAL_DIR_TEL -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3
            if [ $? -eq 0 ]; then
                echo "Mount riuscito in $LOCAL_DIR_TEL"
                notify-send "Mount riuscito in $LOCAL_DIR_TEL"
            else
                echo "Errore durante il mount"
                notify-send "Errore durante il mount"
            fi
        fi
    else
        echo "Telefono non raggiungibile. Controlla se è acceso e connesso alla rete."
        notify-send "Telefono non raggiungibile. Controlla se è acceso e connesso alla rete."
    fi

else
    echo "Usage: $0 [-s | -m]"
    echo "  -s: Unmount"
    echo "  -m: Mount"
    exit 1
fi


