#!/bin/bash

# Carica la configurazione
source "$(dirname "$0")/config.sh"

if [ "$1" == "-s" ]; then
    echo "Unmounting $LOCAL_DIR_SERVER..."
    fusermount -u $LOCAL_DIR_SERVER
    exit 0
elif [ "$1" == "-m" ]; then

    # Controlla se il telefono risponde al ping
    ping -c 1 -W 1 "$IP_SERVER" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        #echo "Telefono raggiungibile. Procedo con il mount..."
        notify-send "GgioDrive raggiungibile. Procedo con il mount..."

        # Controlla se è già montato
        mount | grep "$LOCAL_DIR_SERVER" > /dev/null
        if [ $? -eq 0 ]; then
            #echo "È già montato su $LOCAL_DIR_SERVER"
            notify-send "È già montato su $LOCAL_DIR_SERVER"
        else
            #sshfs -p $PORT_STD $USER_SERVER@$IP_SERVER:$HOME_SERVER $LOCAL_DIR_SERVER -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3
            sshfs -p $PORT_STD $USER_SERVER@$IP_SERVER:$HOME_SERVER $LOCAL_DIR_SERVER -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,uid=$(id -u),gid=$(id -g)

            if [ $? -eq 0 ]; then
                echo "Mount riuscito in $LOCAL_DIR_SERVER"
                notify-send "Mount riuscito in $LOCAL_DIR_SERVER"
            else
                echo "Errore durante il mount"
                notify-send "Errore durante il mount"
            fi
        fi
    else
        echo "GgioaleDrive non raggiungibile. Controlla se è acceso e connesso alla rete."
        notify-send "GgioaleDrive non raggiungibile. Controlla se è acceso e connesso alla rete."
    fi

else
    echo "Usage: $0 [-s | -m]"
    echo "  -s: Unmount"
    echo "  -m: Mount"
    exit 1
fi


