#! /bin/bash

# Carica la configurazione
source "$(dirname "$0")/config.sh"

usage() {
  echo "Usage: $0 [-s | -c | -t] [file] [-s | -c | -t] [where] [-r if recursive]"
  echo "  -s: server"
  echo "  -c: computer"
  echo "  -t: telefono"
  echo "  -h: help"
  echo "Network SCP in order to copy files to various devices in the network."
  echo "(necessita del file config.sh con le variabili di configurazione)"
  echo "Tutte le path partono da home locali"
  echo "ATTENZIONE: PER ORA NON SUPPORTA DA REMOTO A REMOTO"
}

LOCAL_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | grep 100)
echo "Local IP: $LOCAL_IP"

if [ "$1" == "-h" ]; then
  usage
  exit 0

elif [ "$#" -le 3 ]; then
  echo "Invalid number of arguments."
  usage
  exit 1
fi

SOURCE_DISP=""
HOME_SOURCE=""
USER_SOURCE=""

PATHFILE="$2"

DEST_DISP=""
HOME_DEST=""
USER_DEST=""

PATH_DEST="$4"

PORT="$PORT_STD"

#SOURCE
if [ "$1" == "-s" ]; then
  SOURCE_DISP=$IP_SERVER
  HOME_SOURCE=$HOME_SERVER
  USER_SOURCE=$USER_SERVER

elif [ "$1" == "-c" ]; then
  SOURCE_DISP=$IP_COMP
  HOME_SOURCE=$HOME_COMP
  USER_SOURCE=$USER_COMP

elif [ "$1" == "-t" ]; then
  SOURCE_DISP=$IP_TEL
  HOME_SOURCE=$HOME_TEL
  USER_SOURCE=$USER_TEL

elif [ "$1" == "-h" ]; then
  usage
  exit 0

else
  echo "Invalid option. Use -s, -c, or -t."
  usage
  exit 1
fi

#DESTINATION
if [ "$3" == "-s" ]; then
  DEST_DISP=$IP_SERVER
  HOME_DEST=$HOME_SERVER
  USER_DEST=$USER_SERVER

elif [ "$3" == "-c" ]; then
  DEST_DISP=$IP_COMP
  HOME_DEST=$HOME_COMP
  USER_DEST=$USER_COMP

elif [ "$3" == "-t" ]; then
  DEST_DISP=$IP_TEL
  HOME_DEST=$HOME_TEL
  USER_DEST=$USER_TEL
  PORT="$PORT_TEL"

else
  echo "Invalid option. Use -s, -c, or -t."
  usage
  exit 1
fi

if [ $SOURCE_DISP == $LOCAL_IP ]; then
  scp $5 -P $PORT -p $HOME_SOURCE$PATHFILE $USER_DEST@$DEST_DISP:$HOME_DEST$PATH_DEST

elif [ $DEST_DISP == $LOCAL_IP ]; then
  scp $5 -P $PORT -p $USER_SOURCE@$SOURCE_DISP:$HOME_SOURCE$PATHFILE $HOME_DEST$PATH_DEST

else
  # If both source and destination are remote, use the remote copy command
  usage
  exit 1
fi
